#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glActiveVaryingNV_name
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glActiveVaryingNV_name(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glBindAttribLocationARB_name
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glBindAttribLocationARB_name(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glBindAttribLocation_name
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glBindAttribLocation_name(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glBindFragDataLocationEXT_name
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glBindFragDataLocationEXT_name(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glBindFragDataLocationIndexed_name
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glBindFragDataLocationIndexed_name(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glBindFragDataLocation_name
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glBindFragDataLocation_name(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glBinormalPointerEXT_pointer
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glBinormalPointerEXT_pointer(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glBitmap_bitmap
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glBitmap_bitmap(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glBitmapxOES_bitmap
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glBitmapxOES_bitmap(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glCallLists_lists
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glCallLists_lists(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glClearBufferData_data
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glClearBufferData_data(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glClearBufferSubData_data
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glClearBufferSubData_data(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glClearBufferfv_value
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glClearBufferfv_value(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glClearBufferiv_value
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glClearBufferiv_value(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glClearBufferuiv_value
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glClearBufferuiv_value(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glClearNamedBufferDataEXT_data
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glClearNamedBufferDataEXT_data(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glClearNamedBufferSubDataEXT_data
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glClearNamedBufferSubDataEXT_data(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glClearTexImage_data
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glClearTexImage_data(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glColorPointerEXT_pointer
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glColorPointerEXT_pointer(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glColorPointerListIBM_pointer
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glColorPointerListIBM_pointer(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glColorPointer_pointer
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glColorPointer_pointer(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glColorSubTableEXT_data
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glColorSubTableEXT_data(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glColorSubTable_data
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glColorSubTable_data(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glColorTableEXT_table
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glColorTableEXT_table(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glColorTableSGI_table
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glColorTableSGI_table(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glColorTable_table
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glColorTable_table(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glConvolutionFilter1DEXT_image
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glConvolutionFilter1DEXT_image(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glConvolutionFilter1D_image
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glConvolutionFilter1D_image(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glConvolutionFilter2DEXT_image
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glConvolutionFilter2DEXT_image(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glConvolutionFilter2D_image
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glConvolutionFilter2D_image(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glCoverFillPathInstancedNV_paths
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glCoverFillPathInstancedNV_paths(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glCoverFillPathInstancedNV_transformValues
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glCoverFillPathInstancedNV_transformValues(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glCoverStrokePathInstancedNV_paths
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glCoverStrokePathInstancedNV_paths(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glCoverStrokePathInstancedNV_transformValues
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glCoverStrokePathInstancedNV_transformValues(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glCreateShaderProgramEXT_string
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glCreateShaderProgramEXT_string(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glDebugMessageInsert_buf
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glDebugMessageInsert_buf(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glDeformationMap3dSGIX_points
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glDeformationMap3dSGIX_points(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glDeformationMap3fSGIX_points
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glDeformationMap3fSGIX_points(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glDepthRangeArrayv_v
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glDepthRangeArrayv_v(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glDrawArraysIndirect_indirect
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glDrawArraysIndirect_indirect(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glDrawElementsBaseVertex_indices
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glDrawElementsBaseVertex_indices(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glDrawElementsIndirect_indirect
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glDrawElementsIndirect_indirect(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glDrawElementsInstancedARB_indices
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glDrawElementsInstancedARB_indices(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glDrawElementsInstancedBaseVertex_indices
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glDrawElementsInstancedBaseVertex_indices(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glDrawElementsInstancedEXT_indices
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glDrawElementsInstancedEXT_indices(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glDrawElementsInstanced_indices
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glDrawElementsInstanced_indices(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glDrawElements_indices
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glDrawElements_indices(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glDrawPixels_pixels
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glDrawPixels_pixels(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glDrawRangeElementsBaseVertex_indices
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glDrawRangeElementsBaseVertex_indices(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glDrawRangeElementsEXT_indices
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glDrawRangeElementsEXT_indices(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glDrawRangeElements_indices
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glDrawRangeElements_indices(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glEdgeFlagPointerEXT_pointer
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glEdgeFlagPointerEXT_pointer(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glEdgeFlagPointerListIBM_pointer
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glEdgeFlagPointerListIBM_pointer(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glEdgeFlagPointer_pointer
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glEdgeFlagPointer_pointer(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glFogCoordPointerEXT_pointer
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glFogCoordPointerEXT_pointer(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glFogCoordPointerListIBM_pointer
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glFogCoordPointerListIBM_pointer(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glFogCoordPointer_pointer
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glFogCoordPointer_pointer(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetActiveAttribARB_name
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetActiveAttribARB_name(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetActiveAttrib_name
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetActiveAttrib_name(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetActiveUniformARB_name
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetActiveUniformARB_name(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetActiveUniform_name
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetActiveUniform_name(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetActiveVaryingNV_name
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetActiveVaryingNV_name(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetAttachedObjectsARB_obj
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetAttachedObjectsARB_obj(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetAttachedShaders_obj
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetAttachedShaders_obj(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetAttribLocationARB_name
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetAttribLocationARB_name(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetAttribLocation_name
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetAttribLocation_name(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetColorTableEXT_data
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetColorTableEXT_data(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetColorTableSGI_table
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetColorTableSGI_table(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetColorTable_table
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetColorTable_table(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetCompressedMultiTexImageEXT_img
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetCompressedMultiTexImageEXT_img(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetCompressedTexImageARB_img
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetCompressedTexImageARB_img(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetCompressedTexImage_img
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetCompressedTexImage_img(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetCompressedTextureImageEXT_img
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetCompressedTextureImageEXT_img(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetConvolutionFilterEXT_image
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetConvolutionFilterEXT_image(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetConvolutionFilter_image
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetConvolutionFilter_image(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetDebugMessageLogARB_messageLog
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetDebugMessageLogARB_messageLog(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetDebugMessageLog_ids
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetDebugMessageLog_ids(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetDebugMessageLog_lengths
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetDebugMessageLog_lengths(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetDebugMessageLog_messageLog
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetDebugMessageLog_messageLog(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetDebugMessageLog_severities
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetDebugMessageLog_severities(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetDebugMessageLog_sources
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetDebugMessageLog_sources(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetDebugMessageLog_types
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetDebugMessageLog_types(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetFogFuncSGIS_points
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetFogFuncSGIS_points(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetFragDataIndex_name
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetFragDataIndex_name(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetFragDataLocationEXT_name
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetFragDataLocationEXT_name(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetFragDataLocation_name
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetFragDataLocation_name(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetHistogramEXT_values
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetHistogramEXT_values(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetHistogram_values
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetHistogram_values(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetInfoLogARB_infoLog
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetInfoLogARB_infoLog(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetMapParameterfvNV_params
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetMapParameterfvNV_params(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetMapParameterivNV_params
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetMapParameterivNV_params(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetMapdv_v
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetMapdv_v(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetMapfv_v
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetMapfv_v(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetMapiv_v
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetMapiv_v(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetMinmaxEXT_values
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetMinmaxEXT_values(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetMinmax_values
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetMinmax_values(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetMultiTexImageEXT_pixels
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetMultiTexImageEXT_pixels(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetNamedBufferSubDataEXT_data
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetNamedBufferSubDataEXT_data(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetNamedProgramStringEXT_string
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetNamedProgramStringEXT_string(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetPathMetricRangeNV_metrics
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetPathMetricRangeNV_metrics(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetPathMetricsNV_metrics
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetPathMetricsNV_metrics(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetPathMetricsNV_paths
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetPathMetricsNV_paths(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetPathSpacingNV_paths
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetPathSpacingNV_paths(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetPathSpacingNV_returnedSpacing
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetPathSpacingNV_returnedSpacing(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetPixelMapfv_values
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetPixelMapfv_values(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetPixelMapuiv_values
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetPixelMapuiv_values(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetPixelMapusv_values
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetPixelMapusv_values(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetPolygonStipple_mask
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetPolygonStipple_mask(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetProgramBinary_binary
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetProgramBinary_binary(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetProgramInfoLog_infoLog
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetProgramInfoLog_infoLog(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetProgramPipelineInfoLog_infoLog
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetProgramPipelineInfoLog_infoLog(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetProgramResourceIndex_name
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetProgramResourceIndex_name(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetProgramResourceLocationIndex_name
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetProgramResourceLocationIndex_name(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetProgramResourceLocation_name
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetProgramResourceLocation_name(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetProgramStringARB_string
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetProgramStringARB_string(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetProgramStringNV_program
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetProgramStringNV_program(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetSeparableFilterEXT_column
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetSeparableFilterEXT_column(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetSeparableFilterEXT_row
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetSeparableFilterEXT_row(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetSeparableFilterEXT_span
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetSeparableFilterEXT_span(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetSeparableFilter_column
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetSeparableFilter_column(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetSeparableFilter_row
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetSeparableFilter_row(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetSeparableFilter_span
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetSeparableFilter_span(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetShaderInfoLog_infoLog
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetShaderInfoLog_infoLog(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetShaderSourceARB_source
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetShaderSourceARB_source(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetShaderSource_source
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetShaderSource_source(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetSubroutineIndex_name
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetSubroutineIndex_name(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetSubroutineUniformLocation_name
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetSubroutineUniformLocation_name(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetSynciv_values
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetSynciv_values(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetTexFilterFuncSGIS_weights
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetTexFilterFuncSGIS_weights(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetTexImage_pixels
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetTexImage_pixels(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetTextureImageEXT_pixels
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetTextureImageEXT_pixels(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetTransformFeedbackVaryingEXT_name
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetTransformFeedbackVaryingEXT_name(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetTransformFeedbackVarying_name
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetTransformFeedbackVarying_name(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetUniformBlockIndex_uniformBlockName
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetUniformBlockIndex_uniformBlockName(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetUniformLocationARB_name
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetUniformLocationARB_name(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetUniformLocation_name
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetUniformLocation_name(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetUniformdv_params
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetUniformdv_params(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetUniformfvARB_params
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetUniformfvARB_params(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetUniformfv_params
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetUniformfv_params(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetUniformi64vNV_params
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetUniformi64vNV_params(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetUniformivARB_params
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetUniformivARB_params(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetUniformiv_params
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetUniformiv_params(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetUniformui64vNV_params
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetUniformui64vNV_params(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetUniformuivEXT_params
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetUniformuivEXT_params(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetUniformuiv_params
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetUniformuiv_params(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetVaryingLocationNV_name
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glGetVaryingLocationNV_name(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glIndexPointerEXT_pointer
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glIndexPointerEXT_pointer(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glIndexPointerListIBM_pointer
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glIndexPointerListIBM_pointer(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glIndexPointer_pointer
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glIndexPointer_pointer(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glInterleavedArrays_pointer
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glInterleavedArrays_pointer(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glMap1d_points
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glMap1d_points(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glMap1f_points
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glMap1f_points(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glMap2d_points
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glMap2d_points(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glMap2f_points
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glMap2f_points(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glMapControlPointsNV_points
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glMapControlPointsNV_points(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glMapParameterfvNV_params
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glMapParameterfvNV_params(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glMapParameterivNV_params
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glMapParameterivNV_params(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glMapVertexAttrib1dAPPLE_points
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glMapVertexAttrib1dAPPLE_points(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glMapVertexAttrib1fAPPLE_points
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glMapVertexAttrib1fAPPLE_points(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glMapVertexAttrib2dAPPLE_points
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glMapVertexAttrib2dAPPLE_points(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glMapVertexAttrib2fAPPLE_points
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glMapVertexAttrib2fAPPLE_points(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glMatrixIndexPointerARB_pointer
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glMatrixIndexPointerARB_pointer(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glMultiDrawArraysIndirectAMD_indirect
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glMultiDrawArraysIndirectAMD_indirect(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glMultiDrawArraysIndirect_indirect
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glMultiDrawArraysIndirect_indirect(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glMultiDrawElementsIndirectAMD_indirect
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glMultiDrawElementsIndirectAMD_indirect(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glMultiDrawElementsIndirect_indirect
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glMultiDrawElementsIndirect_indirect(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glMultiModeDrawArraysIBM_count
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glMultiModeDrawArraysIBM_count(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glMultiModeDrawArraysIBM_first
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glMultiModeDrawArraysIBM_first(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glMultiModeDrawArraysIBM_mode
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glMultiModeDrawArraysIBM_mode(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glMultiModeDrawElementsIBM_count
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glMultiModeDrawElementsIBM_count(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glMultiModeDrawElementsIBM_indices
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glMultiModeDrawElementsIBM_indices(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glMultiModeDrawElementsIBM_mode
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glMultiModeDrawElementsIBM_mode(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glMultiTexCoordPointerEXT_pointer
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glMultiTexCoordPointerEXT_pointer(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glMultiTexImage1DEXT_pixels
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glMultiTexImage1DEXT_pixels(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glMultiTexImage2DEXT_pixels
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glMultiTexImage2DEXT_pixels(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glMultiTexImage3DEXT_pixels
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glMultiTexImage3DEXT_pixels(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glMultiTexSubImage1DEXT_pixels
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glMultiTexSubImage1DEXT_pixels(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glMultiTexSubImage2DEXT_pixels
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glMultiTexSubImage2DEXT_pixels(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glMultiTexSubImage3DEXT_pixels
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glMultiTexSubImage3DEXT_pixels(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glNamedBufferDataEXT_data
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glNamedBufferDataEXT_data(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glNamedBufferSubDataEXT_data
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glNamedBufferSubDataEXT_data(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glNormalPointerEXT_pointer
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glNormalPointerEXT_pointer(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glNormalPointerListIBM_pointer
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glNormalPointerListIBM_pointer(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glNormalPointer_pointer
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glNormalPointer_pointer(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glObjectLabel_label
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glObjectLabel_label(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glObjectPtrLabel_label
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glObjectPtrLabel_label(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glPathColorGenNV_coeffs
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glPathColorGenNV_coeffs(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glPathCommandsNV_coords
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glPathCommandsNV_coords(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glPathCoordsNV_coords
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glPathCoordsNV_coords(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glPathGlyphRangeNV_fontName
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glPathGlyphRangeNV_fontName(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glPathGlyphsNV_charcodes
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glPathGlyphsNV_charcodes(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glPathGlyphsNV_fontName
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glPathGlyphsNV_fontName(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glPathSubCommandsNV_coords
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glPathSubCommandsNV_coords(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glPathSubCoordsNV_coords
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glPathSubCoordsNV_coords(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glPathTexGenNV_coeffs
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glPathTexGenNV_coeffs(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glPolygonStipple_mask
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glPolygonStipple_mask(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glPushDebugGroup_message
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glPushDebugGroup_message(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glReadPixels_pixels
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glReadPixels_pixels(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glReplacementCodePointerSUN_pointer
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glReplacementCodePointerSUN_pointer(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glReplacementCodeubvSUN_code
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glReplacementCodeubvSUN_code(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glReplacementCodeuivSUN_code
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glReplacementCodeuivSUN_code(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glReplacementCodeusvSUN_code
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glReplacementCodeusvSUN_code(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glScissorArrayv_v
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glScissorArrayv_v(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glSecondaryColorPointerEXT_pointer
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glSecondaryColorPointerEXT_pointer(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glSecondaryColorPointerListIBM_pointer
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glSecondaryColorPointerListIBM_pointer(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glSecondaryColorPointer_pointer
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glSecondaryColorPointer_pointer(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glSeparableFilter2DEXT_column
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glSeparableFilter2DEXT_column(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glSeparableFilter2DEXT_row
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glSeparableFilter2DEXT_row(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glSeparableFilter2D_column
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glSeparableFilter2D_column(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glSeparableFilter2D_row
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glSeparableFilter2D_row(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glSetInvariantEXT_addr
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glSetInvariantEXT_addr(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glSetLocalConstantEXT_addr
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glSetLocalConstantEXT_addr(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glStencilFillPathInstancedNV_paths
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glStencilFillPathInstancedNV_paths(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glStencilFillPathInstancedNV_transformValues
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glStencilFillPathInstancedNV_transformValues(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glStencilStrokePathInstancedNV_paths
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glStencilStrokePathInstancedNV_paths(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glStencilStrokePathInstancedNV_transformValues
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glStencilStrokePathInstancedNV_transformValues(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glStringMarkerGREMEDY_string
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glStringMarkerGREMEDY_string(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glTangentPointerEXT_pointer
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glTangentPointerEXT_pointer(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glTexCoordPointerEXT_pointer
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glTexCoordPointerEXT_pointer(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glTexCoordPointerListIBM_pointer
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glTexCoordPointerListIBM_pointer(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glTexCoordPointer_pointer
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glTexCoordPointer_pointer(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glTexImage1D_pixels
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glTexImage1D_pixels(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glTexImage2D_pixels
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glTexImage2D_pixels(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glTexImage3DEXT_pixels
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glTexImage3DEXT_pixels(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glTexImage3D_pixels
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glTexImage3D_pixels(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glTexImage4DSGIS_pixels
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glTexImage4DSGIS_pixels(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glTexSubImage1DEXT_pixels
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glTexSubImage1DEXT_pixels(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glTexSubImage1D_pixels
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glTexSubImage1D_pixels(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glTexSubImage2DEXT_pixels
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glTexSubImage2DEXT_pixels(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glTexSubImage2D_pixels
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glTexSubImage2D_pixels(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glTexSubImage3DEXT_pixels
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glTexSubImage3DEXT_pixels(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glTexSubImage3D_pixels
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glTexSubImage3D_pixels(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glTexSubImage4DSGIS_pixels
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glTexSubImage4DSGIS_pixels(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glTextureImage1DEXT_pixels
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glTextureImage1DEXT_pixels(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glTextureImage2DEXT_pixels
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glTextureImage2DEXT_pixels(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glTextureImage3DEXT_pixels
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glTextureImage3DEXT_pixels(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glTextureSubImage1DEXT_pixels
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glTextureSubImage1DEXT_pixels(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glTextureSubImage2DEXT_pixels
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glTextureSubImage2DEXT_pixels(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glTextureSubImage3DEXT_pixels
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glTextureSubImage3DEXT_pixels(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glTransformFeedbackAttribsNV_attribs
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glTransformFeedbackAttribsNV_attribs(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glTransformPathNV_transformValues
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glTransformPathNV_transformValues(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glVDPAUGetSurfaceivNV_values
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glVDPAUGetSurfaceivNV_values(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glVariantPointerEXT_addr
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glVariantPointerEXT_addr(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glVertexArrayRangeNV_pointer
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glVertexArrayRangeNV_pointer(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glVertexAttribIPointerEXT_pointer
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glVertexAttribIPointerEXT_pointer(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glVertexAttribIPointer_pointer
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glVertexAttribIPointer_pointer(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glVertexAttribPointerARB_pointer
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glVertexAttribPointerARB_pointer(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glVertexAttribPointerNV_pointer
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glVertexAttribPointerNV_pointer(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glVertexAttribPointer_pointer
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glVertexAttribPointer_pointer(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glVertexPointerEXT_pointer
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glVertexPointerEXT_pointer(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glVertexPointerListIBM_pointer
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glVertexPointerListIBM_pointer(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glVertexPointer_pointer
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glVertexPointer_pointer(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glVertexWeightPointerEXT_pointer
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glVertexWeightPointerEXT_pointer(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glViewportArrayv_v
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glViewportArrayv_v(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glWeightPointerARB_pointer
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glWeightPointerARB_pointer(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glXBindTexImageEXT_attrib_list
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glXBindTexImageEXT_attrib_list(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glXBindVideoDeviceNV_attrib_list
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glXBindVideoDeviceNV_attrib_list(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glXChooseFBConfig_attrib_list
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glXChooseFBConfig_attrib_list(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glXChooseVisual_attribList
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glXChooseVisual_attribList(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glXCreateContextAttribsARB_attrib_list
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glXCreateContextAttribsARB_attrib_list(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glXCreatePbuffer_attrib_list
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glXCreatePbuffer_attrib_list(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glXCreatePixmap_attrib_list
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glXCreatePixmap_attrib_list(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glXCreateWindow_attrib_list
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glXCreateWindow_attrib_list(a,b,c,d,e,f,g,h) -1
#endif
#ifndef DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glXGetVideoDeviceNV_pVideoDevice
   #define DEF_FUNCTION_PARAM_COMPUTE_ARRAY_SIZE_FUNC_glXGetVideoDeviceNV_pVideoDevice(a,b,c,d,e,f,g,h) -1
#endif
